jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "True"
restart-times: "0"
jobs: "25"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
latency-wait: "240"
local-cores: 1
